# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7fd2f9e9e64935190d3529f1f3b1dcde580dc39abb9256c5ef92207bfb6b8ff17c72dce6cc7982d64fc604580339e1a878eb97293b826c44fa231076a5f874

test:
  secret_key_base: 7cbdbb9cb33b61147a12a42c73c297f29e79095bf3375d3ad924620a7fc8572c1d7d1810f4032c9fc1f0e2eaaae0107571ceb1665449c8fdaac68014b8fc70d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
